<?php
/**
 * Firewall / Wordfence guidance tests — pairing+HMAC only, no bypass policy.
 *
 * Scenario matrix (manual QA on staging):
 * - Wordfence Free Enabled and Protecting
 * - Administrator 2FA enabled (HMAC unaffected)
 * - Application Passwords disabled (pairing+HMAC still works)
 * - Rank Math + LiteSpeed Cache active (informational only)
 *
 * Run: php tests/test_firewall_guidance.php
 *
 * @package SEOAuto\SEOHelper
 */

declare(strict_types=1);

define( 'SEOAUTO_HELPER_PREFIX', 'seoauto_helper_' );

$GLOBALS['seoauto_test_options'] = array();

require_once dirname( __DIR__ ) . '/includes/Security/Firewall_Guidance.php';

use SEOAuto\SEOHelper\Security\Firewall_Guidance;

if ( ! function_exists( 'get_option' ) ) {
	function get_option( string $key, $default = false ) {
		return $GLOBALS['seoauto_test_options'][ $key ] ?? $default;
	}
}
if ( ! function_exists( 'update_option' ) ) {
	function update_option( string $key, $value, $autoload = false ): bool {
		$GLOBALS['seoauto_test_options'][ $key ] = $value;
		return true;
	}
}
if ( ! function_exists( 'delete_option' ) ) {
	function delete_option( string $key ): bool {
		unset( $GLOBALS['seoauto_test_options'][ $key ] );
		return true;
	}
}
if ( ! function_exists( 'wp_parse_url' ) ) {
	function wp_parse_url( string $url, int $component = -1 ) {
		return parse_url( $url, $component );
	}
}
if ( ! function_exists( '__' ) ) {
	function __( string $text, string $domain = 'default' ): string {
		return $text;
	}
}
if ( ! function_exists( 'esc_html' ) ) {
	function esc_html( string $text ): string {
		return htmlspecialchars( $text, ENT_QUOTES, 'UTF-8' );
	}
}
if ( ! function_exists( 'esc_html__' ) ) {
	function esc_html__( string $text, string $domain = 'default' ): string {
		return esc_html( __( $text, $domain ) );
	}
}
if ( ! function_exists( 'sanitize_key' ) ) {
	function sanitize_key( string $key ): string {
		return strtolower( preg_replace( '/[^a-z0-9_\-]/', '', $key ) ?? '' );
	}
}

$failed = 0;

/**
 * @param callable():bool $fn
 */
function check( string $msg, callable $fn ): void {
	global $failed;
	try {
		$ok = (bool) $fn();
	} catch ( Throwable $e ) {
		$ok = false;
		$msg .= ' [' . $e->getMessage() . ']';
	}
	if ( $ok ) {
		echo "PASS  {$msg}\n";
		return;
	}
	++$failed;
	echo "FAIL  {$msg}\n";
}

$wordfence_body = '<html><body><h1>403 Forbidden</h1><p>Generated by Wordfence</p></body></html>';
$plugin_body    = '{"code":"seoauto_bad_signature","message":"invalid sig","data":{"status":403}}';

check(
	'detects Wordfence 403 HTML block on /health-check',
	static function () use ( $wordfence_body ): bool {
		$block = Firewall_Guidance::detect_block(
			403,
			$wordfence_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/health-check'
		);
		return null !== $block
			&& $block['source'] === 'wordfence'
			&& $block['endpoint'] === '/wp-json/seoauto/v1/health-check'
			&& $block['method'] === 'POST';
	}
);

check(
	'detects Wordfence 403 on /posts publish endpoint',
	static function () use ( $wordfence_body ): bool {
		$block = Firewall_Guidance::detect_block(
			403,
			$wordfence_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/posts'
		);
		return null !== $block && str_contains( $block['endpoint'], '/posts' );
	}
);

check(
	'plugin JSON 403 (seoauto_*) is NOT treated as Wordfence WAF',
	static function () use ( $plugin_body ): bool {
		$block = Firewall_Guidance::detect_block(
			403,
			$plugin_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/posts'
		);
		return null === $block;
	}
);

check(
	'non-403 HTTP is ignored',
	static fn(): bool => null === Firewall_Guidance::detect_block(
		502,
		$wordfence_body,
		array(),
		'POST',
		'/wp-json/seoauto/v1/posts'
	)
);

check(
	'blocked message includes endpoint path',
	static function () use ( $wordfence_body ): bool {
		$block = Firewall_Guidance::detect_block(
			403,
			$wordfence_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/posts'
		);
		if ( null === $block ) {
			return false;
		}
		$msg = Firewall_Guidance::blocked_message( $block );
		return str_contains( $msg, '/wp-json/seoauto/v1/posts' )
			&& str_contains( $msg, 'Application Password' );
	}
);

check(
	'Live Traffic steps mention Wordfence Tools and manual allowlist',
	static function (): bool {
		$steps = Firewall_Guidance::live_traffic_steps();
		$joined = implode( ' ', $steps );
		return str_contains( $joined, 'Live Traffic' )
			&& str_contains( $joined, 'Wordfence' )
			&& str_contains( $joined, 'không tự allowlist' );
	}
);

check(
	'record_block persists endpoint for admin UI',
	static function () use ( $wordfence_body ): bool {
		Firewall_Guidance::clear_recorded_block();
		$block = Firewall_Guidance::detect_block(
			403,
			$wordfence_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/media'
		);
		if ( null === $block ) {
			return false;
		}
		Firewall_Guidance::record_block( $block );
		$stored = Firewall_Guidance::get_recorded_block();
		return null !== $stored && $stored['endpoint'] === '/wp-json/seoauto/v1/media';
	}
);

check(
	'audit context logs endpoint and error_code wordfence_blocked',
	static function () use ( $wordfence_body ): bool {
		$block = Firewall_Guidance::detect_block(
			403,
			$wordfence_body,
			array(),
			'POST',
			'/wp-json/seoauto/v1/posts'
		);
		if ( null === $block ) {
			return false;
		}
		$ctx = Firewall_Guidance::audit_context( $block, 'self_test' );
		return ( $ctx['error_code'] ?? '' ) === 'wordfence_blocked'
			&& ( $ctx['endpoint'] ?? '' ) === '/wp-json/seoauto/v1/posts';
	}
);

check(
	'no auto bypass / allowlist / disable Wordfence in plugin code',
	static function (): bool {
		$dir   = dirname( __DIR__ ) . '/includes';
		$files = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $dir ) );
		$skip_files = array( 'Activator.php', 'Firewall_Guidance.php' );
		foreach ( $files as $file ) {
			if ( ! $file->isFile() || $file->getExtension() !== 'php' ) {
				continue;
			}
			if ( in_array( $file->getFilename(), $skip_files, true ) ) {
				continue;
			}
			$content = strtolower( file_get_contents( $file->getPathname() ) ?: '' );
			$forbidden = array(
				'wordfence::',
				'wfconfig',
				'wordfencels',
				'bypass_firewall',
				'whitelist_ip',
				'allowlist_ip',
			);
			foreach ( $forbidden as $needle ) {
				if ( str_contains( $content, $needle ) ) {
					return false;
				}
			}
		}
		return true;
	}
);

check(
	'Connection_Manager documents no Application Password / 2FA dependency',
	static function (): bool {
		$src = file_get_contents( dirname( __DIR__ ) . '/includes/Connection/Connection_Manager.php' ) ?: '';
		return str_contains( $src, 'Application Passwords' )
			&& str_contains( $src, '2FA' )
			&& ! str_contains( strtolower( $src ), 'wp_create_application_password' );
	}
);

echo "\n";
if ( $failed > 0 ) {
	echo "FAILED: {$failed}\n";
	exit( 1 );
}
echo "ALL PASS\n";
exit( 0 );
