<?php
/**
 * Wordfence / WAF 403 guidance — log blocked endpoints, show Live Traffic steps.
 *
 * Policy: never auto-disable Wordfence, never allowlist IPs, never bypass firewall.
 * SEOAuto uses pairing + HMAC only (no Application Password, admin password, or 2FA OTP).
 *
 * @package SEOAuto\SEOHelper
 */

declare(strict_types=1);

namespace SEOAuto\SEOHelper\Security;

final class Firewall_Guidance {

	public const ERROR_CODE = 'wordfence_blocked';

	private const OPTION_LAST_BLOCK = 'last_firewall_block';

	/** @var list<string> */
	private const WORDFENCE_BODY_MARKERS = array(
		'wordfence',
		'generated by wordfence',
		'your access to this site has been limited',
		'waf_block',
		'blocked by wordfence',
	);

	/** @var list<string> */
	private const WORDFENCE_HEADER_PREFIXES = array(
		'x-wordfence',
		'x-wf-',
	);

	/**
	 * Detect external firewall block (Wordfence WAF returns 403 before plugin REST runs).
	 *
	 * @param array<string,mixed> $headers
	 * @return array{source:string,http_code:int,endpoint:string,method:string,detected_at:string}|null
	 */
	public static function detect_block(
		int $http_code,
		string $body,
		array $headers,
		string $method,
		string $endpoint
	): ?array {
		if ( $http_code !== 403 ) {
			return null;
		}

		if ( self::is_plugin_json_error( $body ) ) {
			return null;
		}

		$source = self::identify_source( $body, $headers );
		if ( $source === '' ) {
			return null;
		}

		return array(
			'source'      => $source,
			'http_code'   => $http_code,
			'endpoint'    => self::sanitize_endpoint( $endpoint ),
			'method'      => strtoupper( $method ),
			'detected_at' => gmdate( 'c' ),
		);
	}

	/**
	 * @param array<string,mixed> $headers
	 */
	private static function identify_source( string $body, array $headers ): string {
		$lower_body = strtolower( $body );
		foreach ( self::WORDFENCE_BODY_MARKERS as $marker ) {
			if ( str_contains( $lower_body, $marker ) ) {
				return 'wordfence';
			}
		}

		foreach ( $headers as $name => $value ) {
			$lower = strtolower( (string) $name );
			foreach ( self::WORDFENCE_HEADER_PREFIXES as $prefix ) {
				if ( str_starts_with( $lower, $prefix ) ) {
					return 'wordfence';
				}
			}
		}

		return '';
	}

	private static function is_plugin_json_error( string $body ): bool {
		$trim = trim( $body );
		if ( $trim === '' || $trim[0] !== '{' ) {
			return false;
		}
		$decoded = json_decode( $trim, true );
		if ( ! is_array( $decoded ) ) {
			return false;
		}
		$code = (string) ( $decoded['code'] ?? '' );
		return str_starts_with( $code, 'seoauto_' );
	}

	public static function sanitize_endpoint( string $endpoint ): string {
		$path = (string) ( wp_parse_url( $endpoint, PHP_URL_PATH ) ?? $endpoint );
		$path = '/' . ltrim( $path, '/' );
		return $path !== '/' ? rtrim( $path, '/' ) : $path;
	}

	/**
	 * Persist last blocked endpoint for admin UI (no firewall mutation).
	 *
	 * @param array{source:string,http_code:int,endpoint:string,method:string,detected_at:string} $block
	 */
	public static function record_block( array $block ): void {
		update_option( SEOAUTO_HELPER_PREFIX . self::OPTION_LAST_BLOCK, $block, false );
	}

	/**
	 * @return array{source:string,http_code:int,endpoint:string,method:string,detected_at:string}|null
	 */
	public static function get_recorded_block(): ?array {
		$raw = get_option( SEOAUTO_HELPER_PREFIX . self::OPTION_LAST_BLOCK, array() );
		if ( ! is_array( $raw ) || empty( $raw['endpoint'] ) ) {
			return null;
		}
		return array(
			'source'      => sanitize_key( (string) ( $raw['source'] ?? 'wordfence' ) ),
			'http_code'   => (int) ( $raw['http_code'] ?? 403 ),
			'endpoint'    => self::sanitize_endpoint( (string) $raw['endpoint'] ),
			'method'      => strtoupper( (string) ( $raw['method'] ?? 'POST' ) ),
			'detected_at' => (string) ( $raw['detected_at'] ?? '' ),
		);
	}

	public static function clear_recorded_block(): void {
		delete_option( SEOAUTO_HELPER_PREFIX . self::OPTION_LAST_BLOCK );
	}

	/**
	 * Human-readable failure message including blocked endpoint.
	 *
	 * @param array{source:string,http_code:int,endpoint:string,method:string,detected_at:string} $block
	 */
	public static function blocked_message( array $block ): string {
		unset( $block ); // Keep signature; UI hides technical endpoint details.
		return __(
			'Bảo mật Wordfence đang chặn kết nối từ SEOAuto. Plugin không dùng mật khẩu Administrator hay mã 2FA — chỉ dùng mã ghép nối.',
			'seoauto-seo-helper'
		);
	}

	/**
	 * Step-by-step Live Traffic instructions (manual review only).
	 *
	 * @return list<string>
	 */
	public static function live_traffic_steps(): array {
		return array(
			__( 'Vào Wordfence → Tools → Live Traffic.', 'seoauto-seo-helper' ),
			__( 'Tìm các yêu cầu bị chặn gần thời điểm lỗi.', 'seoauto-seo-helper' ),
			__( 'Nếu cần, tự thêm quy tắc cho phép trong Wordfence. SEOAuto không tự tắt Wordfence.', 'seoauto-seo-helper' ),
		);
	}

	/**
	 * Render admin notice HTML for blocked endpoint + Live Traffic guidance.
	 *
	 * @param array{source:string,http_code:int,endpoint:string,method:string,detected_at:string} $block
	 */
	public static function render_notice( array $block ): void {
		echo '<div class="notice notice-warning inline seoauto-helper-firewall-notice"><p>';
		echo '<strong>' . esc_html__( 'Wordfence đang chặn kết nối SEOAuto', 'seoauto-seo-helper' ) . '</strong><br />';
		echo esc_html( self::blocked_message( $block ) );
		echo '<br /><br /><strong>' . esc_html__( 'Cách kiểm tra', 'seoauto-seo-helper' ) . '</strong>';
		echo '<ol class="seoauto-helper-firewall-steps" style="margin:8px 0 0 18px;">';
		foreach ( self::live_traffic_steps() as $step ) {
			echo '<li>' . esc_html( $step ) . '</li>';
		}
		echo '</ol></div>';
	}

	/**
	 * Audit context for firewall block (endpoint logged explicitly).
	 *
	 * @param array{source:string,http_code:int,endpoint:string,method:string,detected_at:string} $block
	 * @return array<string,mixed>
	 */
	public static function audit_context( array $block, string $action_source = 'self_test' ): array {
		return array(
			'status'     => 'error',
			'error_code' => self::ERROR_CODE,
			'endpoint'   => $block['endpoint'],
			'method'     => $block['method'],
			'http_code'  => $block['http_code'],
			'source'     => $block['source'],
			'via'        => $action_source,
		);
	}
}
